name: Python Environment

on:
  # To run manually
  push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
    
    - name: Install Python dependencies
      run: |
        python -m pip install matplotlib numpy

    - name: Hello World 
      run: |
        python -c "import numpy as np; print('Numpy version: '+np.__version__)"
        python -c "import matplotlib as mpl; print('Matplotlib version: '+mpl.__version__)"
